version: 2
builds:
  - id: gh-pr-summarizer
    binary: gh-pr-summarizer
    main: ./cmd/gh-pr-summarizer/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

universal_binaries:
  - id: gh-pr-summarizer
    replace: true
    name_template: "gh-pr-summarizer"

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: simonmittag
    name: gh-pr-summarizer

brews:
  - name: gh-pr-summarizer
    homepage: https://github.com/simonmittag/gh-pr-summarizer
    repository:
      owner: simonmittag
      name: homebrew-cli
    commit_author:
      name: simonmittag
      email: simonmittag@gmail.com
    description: "Opinionated CLI utility to generate pull request summaries"
    license: "Apache-2.0"
    install: |
      bin.install "gh-pr-summarizer"
